site_name: My Docs

nav:
  - Home: index.md
  - template: template.md
  - Archiving & Secure Storage:
      - Tella: tella.md
      - Picocrypt: 
  - Communication:
      - Briar: Briar.md
      - Bridgefy: 
      - JAMI: 
      - SMS without Border: 
  - Restoring internet access:
      - Iodine: iodine-new.md
      - E-SIM:
  - Media Authentication: 
    - proofmode:  
    - 
  - Browser:
    - Ceno Browser:
    - Tor:
  - Mesh Network:
    - Meshtastic: meshtastic.md

theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - tags
