site_name: My Docs

nav:
  - Home: index.md
  - template: template.md
  - Archiving & Secure Storage:
      - Tella: tella.md
      - Save: OpenArchive.md
  - Communication:
      - Briar: Briar.md
  - Restoring internet access:
      - Iodine: iodine-new.md
      - E-SIM: e-sim.md
  - Mesh Network:
    - Meshtastic: meshtastic.md

theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - tags
